sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com bionic-proposed main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com bionic-updates main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com bionic main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com focal-proposed main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com focal-updates main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com focal main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com jammy-proposed main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com jammy-updates main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com jammy main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com kinetic-proposed main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com kinetic-updates main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com kinetic main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com trusty-proposed main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com trusty-security main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com trusty-updates main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com trusty main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com xenial-proposed main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com xenial-updates main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb http://ddebs.ubuntu.com xenial main restricted universe multiverse partner"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ bookworm-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ bookworm-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ bookworm main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ bullseye-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ bullseye-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ bullseye main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ buster-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ buster-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ buster main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ Debian8.11 main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ Debian9.13 main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ Debian10.13 main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ Debian11.5 main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ jessie-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ jessie main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ oldoldoldstable-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ oldoldoldstable main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ oldoldstable-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ oldoldstable-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ oldoldstable main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ oldstable-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ oldstable-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ oldstable main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ rc-buggy main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ stable-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ stable-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ stable main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ stretch-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ stretch-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/debian/ stretch main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ bookworm-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ bookworm-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ bookworm main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ bullseye-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ bullseye-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ bullseye main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ buster-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ buster-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ buster main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ Debian8.11 main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ Debian9.13 main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ Debian10.13 main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ Debian11.5 main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ jessie-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ jessie main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ oldoldoldstable-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ oldoldoldstable main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ oldoldstable-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ oldoldstable-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ oldoldstable main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ oldstable-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ oldstable-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ oldstable main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ rc-buggy main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ stable-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ stable-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ stable main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ stretch-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ stretch-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.up.pt/pub/debian/ stretch main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ Debian8.11 main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ Debian9.13 main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ Debian10.13 main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ Debian11.5 main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ bookworm-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ bookworm main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ bullseye-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ bullseye-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ bullseye main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ buster-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ buster-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ buster main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ jessie-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ jessie main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ oldoldoldstable-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ oldoldoldstable main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ oldoldstable-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ oldoldstable-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ oldoldstable main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ oldstable-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ oldstable-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ oldstable main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ rc-buggy main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ stable-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ stable-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ stable main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ stretch-proposed-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ stretch-updates main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.de.debian.org/ stretch main contrib non-free non-free-firmware"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ Debian8.11 main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ Debian9.13 main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ Debian10.13 main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ Debian11.5 main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ bookworm-proposed-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ bookworm-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ bookworm main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ bullseye-proposed-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ bullseye-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ bullseye main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ buster-proposed-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ buster-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ buster main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ jessie-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ jessie main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ oldoldoldstable-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ oldoldoldstable main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ oldoldstable-proposed-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ oldoldstable-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ oldoldstable main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ oldstable-proposed-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ oldstable-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ oldstable main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ proposed-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ rc-buggy main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ stable-proposed-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ stable-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ stable main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ stretch-proposed-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ stretch-updates main contrib non-free"
sudo add-apt-repository -ys "deb https://ftp.debian.org/debian/ stretch main contrib non-free"
sudo add-apt-repository -ys "deb https://dl.winehq.org/wine-builds/debian/ bookworm main"
sudo add-apt-repository -ys "deb https://dl.winehq.org/wine-builds/debian/ bullseye main"
sudo add-apt-repository -ys "deb https://dl.winehq.org/wine-builds/debian/ buster main"
sudo add-apt-repository -ys "deb https://dl.winehq.org/wine-builds/debian/ jessie main"
sudo add-apt-repository -ys "deb https://dl.winehq.org/wine-builds/debian/ oldstable main"
sudo add-apt-repository -ys "deb https://dl.winehq.org/wine-builds/debian/ stable main"
sudo add-apt-repository -ys "deb https://dl.winehq.org/wine-builds/debian/ stretch main"
sudo add-apt-repository -ys "deb https://dl.winehq.org/wine-builds/debian/ wheezy main"
sudo add-apt-repository -ys "deb-src https://dl.winehq.org/wine-builds/debian/ bookworm main"
sudo add-apt-repository -ys "deb-src https://dl.winehq.org/wine-builds/debian/ bullseye main"
sudo add-apt-repository -ys "deb-src https://dl.winehq.org/wine-builds/debian/ buster main"
sudo add-apt-repository -ys "deb-src https://dl.winehq.org/wine-builds/debian/ jessie main"
sudo add-apt-repository -ys "deb-src https://dl.winehq.org/wine-builds/debian/ oldstable main"
sudo add-apt-repository -ys "deb-src https://dl.winehq.org/wine-builds/debian/ stable main"
sudo add-apt-repository -ys "deb-src https://dl.winehq.org/wine-builds/debian/ stretch main"
sudo add-apt-repository -ys "deb-src https://dl.winehq.org/wine-builds/debian/ wheezy main"

